config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'invitations/cards'

  get 'invitations/envelopes'

  get 'non_edibles/shades'

  get 'non_edibles/fans'

  get 'non_edibles/candle'

  get 'edibles/tea'

  get 'edibles/jam'

  get 'edibles/honey'

  get 'edibles/cakes'

  get 'edibles/coffee'

  get 'edibles/macarons'

  get 'edibles/cookies'

  get 'pages/home'

  get 'pages/products'

  get 'pages/about'

  get 'pages/contact'

  resources :contact, only: [:index, :new, :create]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,  :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :contact_number, :validate => /\A[+-]?\d+\z/
  attribute :message
  attribute :nickname, :captcha => true

  def headers
    {
      :subject => "Altogether Enquiry",
      :to => "letsget@altogether.sg",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @contact = Contact.new(params[:contact])
    @disable_product_list = true
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    respond_to do |format|
      if @contact.deliver
        @contact = Contact.new
        format.html { render 'index'}
        format.js {flash.now[:success] = @message = "Thank you for your message. We'll get back to you soon!" }
      else
        format.html { render 'index'}
        format.js {flash.now[:danger] = @message = "There were some errors in the field. Pls try again." }
      end
    end
  end
end

app/controllers/edibles_controller.rb
class EdiblesController < ApplicationController
  def tea
  end

  def jam
  end

  def honey
  end

  def cakes
  end

  def coffee
  end

  def macarons
  end

  def cookies
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  def cards
  end

  def envelopes
  end
end

app/controllers/non_edibles_controller.rb
class NonEdiblesController < ApplicationController
  def shades
  end

  def fans
  end

  def candle
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def products
  end

  def about
    @disable_product_list = true
  end

  def contact
    @disable_product_list = true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/edibles_helper.rb
module EdiblesHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/non_edibles_helper.rb
module NonEdiblesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contact/_contact_form.html.erb
<%= form_for @contact, url: contact_index_path, remote: true do |f| %>
  <div class="col-xs-5" id="contact_form"%>
    <%= f.label "Your Name", class: "contact_title" %> <br>
    <%= f.text_field :name, required: true, class: "contact_form_text_area" %> <br>

    <%= f.label "Your Email", class: "contact_title" %> <br>
    <%= f.text_field :email, required: true, class: "contact_form_text_area" %> <br>

    <%= f.label "Your Contact Number", class: "contact_title" %> <br>
    <%= f.text_field :contact_number, required: true, class: "contact_form_text_area" %> <br>

    <%= f.label "Your Message", class: "contact_title" %> <br>
    <%= f.text_area :message, rows: 8, cols: 60, required: true, class: "contact-form-text-area",
                              placeholder: "Send a message to Altogether." %> <br>

    <div class="hidden">
      <%= f.label :nickname %>
      <%= f.text_field :nickname, :hint => 'Leave this field blank!'%>
    </div>

    <%= f.submit "Send Message", class: 'message_button' %>
  </div>

  <% end %>

  <div class="col-xs-6" id="flash-message">
    <%= render 'flash' %>
  </div>

app/views/contact/_flash.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/contact/create.js.erb
$('#contact').html("<%= j render 'contact_form' %>");
$('#flash-message').html("<%= j render 'flash' %>").delay(3000).fadeOut(4000);

app/views/contact/index.html.erb
<div class="row">
  <div class="col-xs-6">
    <div id="info">
      <p id="hello">Hello</p>
      <p id="email">Email</p>
      <p>letsget@altogether.sg</p>
    </div>
  </div>
    <div id="contact">
      <%= render 'contact_form' %>
    </div>
</div>

app/views/edibles/cakes.html.erb
<% content_for :background do%>
<div id="background_cakes"></div>
<% end %>

<% content_for :image do %>
<div class="col-xs-4" id="image_container">
  <%= image_tag "cakes.png", class: "img"%>
</div>

<div class="col-xs-3" class="mobile_description">
  <p class="product_description">Baked with distinctive ring shape inspired by a traditional European cake. Delicious to consume at room temperature, the bundt cakes offer your guests the perfect compliment to your joyous event.</p>
</div>
<% end %>

app/views/edibles/coffee.html.erb
<% content_for :background do%>
<div id="background_coffee"></div>
<% end %>

<% content_for :image do %>
<div class="col-xs-4" id="image_container">
  <%= image_tag "coffee.png", class: "img"%>
</div>

<div class="col-xs-3" class="mobile_description">
  <p class="product_description">Coffee can bring with it some surprising perks. Gift your guests ground coffee packed in test tube jars.</p>
</div>
<% end %>

app/views/edibles/cookies.html.erb
<% content_for :background do%>
<div id="background_cookies"></div>
<% end %>

<% content_for :image do %>
<div class="col-xs-4" id="image_container">
  <%= image_tag "cookies.png", class: "img"%>
</div>

<div class="col-xs-3" class="mobile_description">
  <p class="product_description">A descent from cakes and other sweetened breads, the cookie in almost all its forms remains a favourite comfort dessert.</p>
</div>
<% end %>

app/views/edibles/honey.html.erb
<% content_for :background do%>
<div id="background_honey"></div>
<% end %>

<% content_for :image do %>
<div class="col-xs-4" id="image_container">
  <%= image_tag "honey.png", class: "img"%>
</div>

<div class="col-xs-3" class="mobile_description">
  <p class="product_description">Relatively as sweet as granulated sugar, honey has an attractive and a distinctive flavor when used as a sweetener. What better gift to give your guests that goes along to your sweet and memorable event.</p>
</div>
<% end %>

app/views/edibles/jam.html.erb
<% content_for :background do%>
<div id="background_jam"></div>
<% end %>

<% content_for :image do %>
<div class="col-xs-4" id="image_container">
  <%= image_tag "jam.png", class: "img"%>
</div>

<div class="col-xs-3" class="mobile_description">
  <p class="product_description">Containing both the juice and flesh of a fruit, jam spreads are a delicacy that can be enjoyed in a variety of ways.</p>
</div>
<% end %>

app/views/edibles/macarons.html.erb
<% content_for :background do%>
<div id="background_macarons"></div>
<% end %>

<% content_for :image do %>
<div class="col-xs-4" id="image_container">
  <%= image_tag "macarons.png", class: "img"%>
</div>

<div class="col-xs-3 mobile_description">
  <p class="product_description">Sharing a cake is a magical moment of festivity and emotion. Guests will enjoy this beautiful treat that will make your event a more memorable one.</p>
</div>
<% end %>

app/views/edibles/tea.html.erb
<% content_for :background do%>
<div id="background_tea"></div>
<% end %>

<% content_for :image do %>
<div class="col-xs-4" id="image_container">
  <%= image_tag "tea.png", class: "img"%>
</div>

<div class="col-xs-3" class="mobile_description">
  <p class="product_description">An aromatic beverage commonly prepared by everyone. Let your guests enjoy a cup of cured leaves to unwind and relax with either our House or Premium selection for you to choose from.</p>
</div>
<% end %>

app/views/invitations/cards.html.erb
<% content_for :background do%>
<div id="background_cards"></div>
<% end %>

<% content_for :image do %>
<div class="col-xs-4" id="image_container">
  <%= image_tag "cards.png", class: "img"%>
</div>

<div class="col-xs-3" class="mobile_description">
  <p class="product_description">Announce your special day to your guests with modern, unique wedding invitations and elegant stationery.</p>
</div>
<% end %>

app/views/invitations/envelopes.html.erb
<% content_for :background do%>
<div id="background_envelopes"></div>
<% end %>

<% content_for :image do %>
<div class="col-xs-4" id="image_container">
  <%= image_tag "envelopes2.png", class: "img"%>
</div>

<div class="col-xs-3" class="mobile_description">
  <p class="product_description">Distinct designs, attractive colours and a premium finish that will offer you everything you ever wanted for your wedding invitations.</p>
</div>
<% end %>

app/views/layouts/_background.html.erb
<div id="background"></div>

app/views/layouts/_footer.html.erb
<div class="row footer">
  <div class="col-xs-6" id="social_media">
    <a href="https://facebook.com/altogether.sg/" target="_blank">Facebook</a>
    <a href="http://instagram.com/altogether.sg" target="_blank">Instagram</a>
  </div>
  <div class="col-xs-6">
    <div>
      <p id="copyright">&#169 Copyright 2017 Altogether</p>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="row navbar header" id="branding">
  <div class="col-xs-6">
    <div id="logo">
      <%= image_tag ("logo.png") %>
    </div>
    <div id="tagline">
      <%= image_tag ("tagline.png") %>
    </div>

  </div>
  <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#dropdown">
    <span class="glyphicon glyphicon-menu-hamburger"></span>﻿
  </button>

  <div class="col-xs-6" id="navigation">
    <div class="collapse navbar-collapse" id="dropdown">
      <ul class="active">
        <li class="current-item"><%= link_to "Home", pages_home_path %></li>
        <li><%= link_to "About", pages_about_path %></li>
        <li><%= link_to "Contact", contact_index_path %></li>
      </ul>
    </div>


  </div>
</div>

app/views/layouts/_mobile_layout.html.erb
<div class="row" id="mobile_layout">
  <div class="col-xs-12">
    <div class="dropdown">
      <h5><button onclick="edibles_click()" class="dropbtn">Edibles</button></h5>
      <div id="edibles_dropdown" class="dropdown-content">
        <%= link_to "Tea", edibles_tea_path%>
        <%= link_to "Jam", edibles_jam_path%>
        <%= link_to "Honey", edibles_honey_path%>
        <%= link_to "Bundt Cakes", edibles_cakes_path%>
        <%= link_to "Coffee", edibles_coffee_path%>
        <%= link_to "Macarons", edibles_macarons_path%>
        <%= link_to "Cookies", edibles_cookies_path%>
      </div>
    </div>
    <hr>
    <%= image_tag 'fans.png', class: "img", id: "mobile_layout"%>
    <div class="dropdown">
      <h5><button onclick="non_edibles_click()" class="dropbtn">Non-Edibles</button></h5>
      <div id="non_edibles_dropdown" class="dropdown-content">
        <%= link_to "Fans", non_edibles_fans_path%>
        <%= link_to "Shades", non_edibles_shades_path%>
        <%= link_to "Candle", non_edibles_candle_path%>
      </div>
    </div>
    <hr>
  </div>
</div>
<div class="row" id="mobile_layout">
  <div class="col-xs-12">
    <%= image_tag 'cards.png', class: "img", id: "mobile_layout"%>
    <h5><%= link_to "Cards", invitations_cards_path, id: 'cards'%></h5>
    <hr>
  </div>
</div>
<div class="row" id="mobile_layout">
  <div class="col-xs-12">
    <%= image_tag 'envelopes1.png', class: "img", id: "mobile_layout"%>
    <h5><%= link_to "Envelopes", invitations_envelopes_path, id: 'envelopes'%></h5>
    <hr>
  </div>
</div>

app/views/layouts/_product_list.html.erb
<div class="row">
  <div class="col-xs-3" id="product_links">
    <h4>Favours</h4>
    <ul>
      <div class="dropdown_edibles">
        <li id="edibles">Edibles</li>
        <div class="dropdown_edibles_content">
          <%= link_to "Tea", edibles_tea_path%>
          <%= link_to "Jam", edibles_jam_path%>
          <%= link_to "Honey", edibles_honey_path%>
          <%= link_to "Bundt Cakes", edibles_cakes_path%>
          <%= link_to "Coffee", edibles_coffee_path%>
          <%= link_to "Macarons", edibles_macarons_path%>
          <%= link_to "Cookies", edibles_cookies_path%>
        </div>
      </div>
      <div class="dropdown_non_edibles">
        <li id="non-edibles">Non-Edibles</li>
        <div class="dropdown_non_edibles_content">
          <%= link_to "Fans", non_edibles_fans_path%>
          <%= link_to "Shades", non_edibles_shades_path%>
          <%= link_to "Candle", non_edibles_candle_path%>
        </div>
      </div>
    </ul>
    <h4>Invitations</h4>
    <ul>
      <li><%= link_to "Cards", invitations_cards_path, id: 'cards'%></li>
      <li><%= link_to "Envelopes", invitations_envelopes_path, id: 'envelopes'%></li>
    </ul>
  </div>
  <%= yield(:image) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Altogether</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>

  <body>
    <%= yield(:background)%>
    <div class="container" id=main_page>
      <%= render partial: "layouts/header" %>
      <%= render partial: "layouts/product_list" unless @disable_product_list %>
      <%= yield %>
      <%= render partial: "layouts/footer" %>

  </div>
  </body>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/non_edibles/candle.html.erb
<% content_for :background do%>
<div id="background_candle"></div>
<% end %>

<% content_for :image do %>
<div class="col-xs-4" id="image_container">
  <%= image_tag "candles.png", class: "img"%>
</div>

<div class="col-xs-3 mobile_description">
  <p class="product_description">A precious fragrance to warm the air, ladened with vanilla essence. Particularly to set a soft, warm, or romantic ambiance, the scented candles serve as the perfect gift to diffuse your story to your guests.</p>
</div>
<% end %>

app/views/non_edibles/fans.html.erb
<% content_for :background do%>
<div id="background_fans"></div>
<% end %>

<% content_for :image do %>
<div class="col-xs-4" id="image_container">
  <%= image_tag "fans.png", class: "img"%>
</div>

<div class="col-xs-3" class="mobile_description">
  <p class="product_description">Beautiful as they are functional, fashioned out of decorative paper and wood. Make it your own by engraving your names and dates on the side to etch your occasion into your guests’ hearts. Paper fans come in a variety of colours.</p>
</div>
<% end %>

app/views/non_edibles/shades.html.erb
<% content_for :background do%>
<div id="background_shades"></div>
<% end %>

<% content_for :image do %>
<div class="col-xs-4" id="image_container">
  <%= image_tag "shades.png", class: "img"%>
</div>

<div class="col-xs-3" class="mobile_description">
  <p class="product_description">Love is so bright that your guests have to put on the shades. Bring on the smiles and good times with an eccentric gift that will make your event truly memorable.</p>
</div>
<% end %>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-md-6">
    <div id="about_description">
      <h2>About</h2>
      <p>Hi, we’re a collective that loves minimal design.</p>

      <p>
        ALTOGETHER designs invitations and gift favours to fit the theme of your occasion. Our passion is executing your ideas to realise your dream event.
      </p>
    </div>
  </div>
    <div class="col-md-6">
      <%= image_tag "about_pic2.png", class: "about_image"%>
    </div>
  </div>


<div class="row">
  <div class="col-md-6 col-md-push-6">
    <div id="do_description">
      <h2>What We Do</h2>
      <p>We specialise in packaging design that is as functional as it is good looking. We always aim to deliver a sharp, bespoke design solution. We love crafting and communicating your story that you want to relate to the guests of your event.</p>
    </div>
  </div>
  <div class="col-md-6 col-md-pull-6">
    <%= image_tag "envelopes1.png", class: "about_image", id:"do_image"%>
  </div>
</div>

app/views/pages/home.html.erb
<div id="desktop_view">
  <% content_for :background do%>
  <div id="background"></div>
  <% end %>

  <% content_for :image do %>
  <div class="col-xs-4" id="image_container">
    <%= image_tag "tea.png", class: "img", id:"image_change"%>
  </div>

  <div class="col-xs-3" id="description">
    <p class="product_description" id="description_change">An aromatic beverage commonly prepared by everyone. Let your guests enjoy a cup of cured leaves to unwind and  relax with either our House or Premium selection for you to choose from.</p>
  </div>
  <% end %>
</div>
<%= render partial: "layouts/mobile_layout" %>